#!/bin/bash
version=$1

if [[ ! -d "./Wishlist.xcodeproj" ]] ; then
  echo "Script must be run in project directory"; exit 1
fi
if [[ ! $version =~ ^[0-9]+(\.[0-9]+){2,2}$ ]]; 
then
  echo "Script must be run with version number as argument"; exit 1
fi

echo " #### Building Docker image for project Wishlist with version $version"

docker build -f Docker/docker -t "wishlist:$version" .

