#!/bin/bash
project=Wishlist
version=$1
label=$(echo "$project" | tr "[:upper:]" "[:lower:]")
echo
source "./Docker/functions"
check_version

docker_build_swift

echo "🐳 BUILDING IMAGE: Project $project with version $version"

out=$(docker build -f Docker/docker -t "$label:$version" . 2>&1)
[ $? -ne 0 ] \
    && echo "$out" \
    && echo "⛔ Docker build command failed!" \
    && exit 1

image=$(docker image ls | grep -E "^$label\s+$version " | tr -s ' ' | cut -d' ' -f 1,2,3)
echo "😎 BUILD IMAGE: $image"
