#!/bin/bash
project=Wishlist
version=$1
label=$(echo "$project" | tr "[:upper:]" "[:lower:]")
echo
source "./Docker/functions"
check_version

echo "🐳 PUSHING IMAGE: Project $project with version $version"

check_tagged_image "$label" "$version"

out=$(docker push yamanote/private:$label-$version)
[ $? -ne 0 ] \
    && echo "$out" \
    && echo "⛔ Docker push command failed!" \
    && exit 1

image=$(docker image ls | grep "$label\-$version " | tr -s ' ' | cut -d' ' -f 1,2,3)
echo "😎 PUSHED IMAGE: $image"
