#!/bin/bash
project=Wishlist
version=$1
label=$(echo "$project" | tr "[:upper:]" "[:lower:]")

echo

if [[ ! -d "./$project.xcodeproj" ]] ; then
  echo "🤔 Script must be run in project directory ..."; exit 1
fi
if [[ ! $version =~ ^[0-9]+(\.[0-9]+){2,2}(\-RC[0-9]+){0,1}$ ]];
then
  echo "🤔 Script must be run with version number as argument ..."; exit 1
fi

echo "🐳 PUSHING Docker image for project $project with version $version"

image=$(docker image ls | grep "$label\-$version " | tr -s ' ' | cut -d' ' -f 1,2,3)
[ -z "$image" ] \
    && echo "⛔ Image not found for version $version!" \
    && echo "💡 Run build command first ..." \
    && echo "💡 Run tag command next ..." \
    && exit 1

out=$(docker push yamanote/private:$label-$version)
[ $? -ne 0 ] \
    && echo "$out" \
    && echo "⛔ Docker push command failed!" \
    && exit 1

echo "😎 PUSHED $image"
