#!/bin/bash
version=$1
mode=$2

if [[ ! -d "./Wishlist.xcodeproj" ]] ; then
  echo "Script must be run in project directory"; exit 1
fi
if [[ ! $version =~ ^[0-9]+(\.[0-9]+){2,2}(\-RC[0-9]+){0,1}$ ]] ; then
  echo "Script must be run with version number as first argument"; exit 1
fi
if [[ ! $mode =~ ^prod|dev$ ]] ; then
  echo "Script must be run with mode ("prod", "dev") as second argument"; exit 1
fi

echo " #### Running Docker Compose for project Wishlist with version $version in $mode"

APPVERSION=$version APPENV=$mode DBHOST=db docker-compose -p wishlist -f Docker/docker-compose up

