#!/bin/bash
project=Wishlist
version=$1
mode=$2
label=$(echo "$project" | tr "[:upper:]" "[:lower:]")
echo
source "./Docker/functions"
check_version_and_mode

echo "🐳 RUNNING Docker compose for project $project with version $version in $mode"

APPVERSION=$version APPENV=$mode DBHOST=db docker-compose -p $label -f Docker/docker-compose up -d db
sleep 10s
APPVERSION=$version APPENV=$mode DBHOST=db docker-compose -p $label -f Docker/docker-compose up
