#!/bin/bash
project=Wishlist
version=$1
label=$(echo "$project" | tr "[:upper:]" "[:lower:]")
echo
source "./Docker/functions"
check_version

echo "🐳 TAGGING IMAGE: Project $project with version $version"

check_image "$version"

docker tag $image yamanote/private:$label-$version
[ $? -ne 0 ] \
    && echo "⛔ Docker tag command failed!" \
    && exit 1

image=$(docker image ls | grep "$label\-$version " | tr -s ' ' | cut -d' ' -f 1,2,3)
echo "😎 TAGGED IMAGE: $image"

exit 0
