#!/bin/bash
project=Wishlist
version=$1
label=$(echo "$project" | tr "[:upper:]" "[:lower:]")

echo

if [[ ! -d "./$project.xcodeproj" ]] ; then
  echo "🤔 Script must be run in project directory ..."; exit 1
fi
if [[ ! $version =~ ^[0-9]+(\.[0-9]+){2,2}(\-RC[0-9]+){0,1}$ ]];
then
  echo "🤔 Script must be run with version number as argument ..."; exit 1
fi

echo "🐳 TAGGING Docker image for project $project with version $version"

image=$(docker image ls | grep " $version " | tr -s ' ' | cut -d' ' -f 3)
[ -z "$image" ] \
    && echo "⛔ Image not found for version $version!" \
    && echo "💡 Run build command first ..." \
    && exit 1

docker tag $image yamanote/private:$label-$version
[ $? -ne 0 ] \
    && echo "⛔ Docker tag command failed!" \
    && exit 1

image=$(docker image ls | grep "$label\-$version " | tr -s ' ' | cut -d' ' -f 1,2,3)
echo "😎 TAGGED $image"

exit 0
