#!/bin/bash
project=Wishlist
version=$1
label=$(echo "$project" | tr "[:upper:]" "[:lower:]")
echo
source "./Docker/functions"
check_version

docker_build_swift

echo "🐳 RUNNING TESTS: Project $project with version $version"

docker_compose_in="$(cat <<-EOF
version: "3.3"
services:
  app-test:
    container_name: wishlist-app-test
    command: sh -c 'swift build --configuration debug -Xswiftc "-suppress-warnings" -Xswiftc "-g" --build-path "./.build_docker_test" && swift test --skip-update --build-path "./.build_docker_test"'
    image: "wishlist:swift"
    environment:
      SITE_URL: "http://localhost:8080"
      SITE_RELEASE: "beta"
      SITE_ACCESS: "all"
      DBHOST: "db-test"
    working_dir: /app
    volumes:
      - ./:/app
    links:
      - db-test
    depends_on:
      - db-test
  db-test:
    container_name: wishlist-db-test
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: wishlist
      MYSQL_USER: wishlist
      MYSQL_PASSWORD: wishlist
      MYSQL_DATABASE: wishlist
EOF
)"

echo "$docker_compose_in" | APPVERSION=$version docker-compose -p $label -f - up --abort-on-container-exit
[ $? -ne 0 ] \
    && echo "⛔ Docker compose command failed!" \
    && exit 1

echo "😎 RUN TESTS: Project $project with version $version"
